import Foundation

public struct CloudAPIConfig: Sendable {
    public let apiKey: String
    public let baseURL: URL
    public let timeout: TimeInterval
    public let maxRetries: Int
    public let extraHeaders: [String: String]

    public init(
        apiKey: String,
        baseURL: URL,
        timeout: TimeInterval = 60.0,
        maxRetries: Int = 3,
        extraHeaders: [String: String] = [:]
    ) {
        self.apiKey = apiKey
        self.baseURL = baseURL
        self.timeout = timeout
        self.maxRetries = maxRetries
        self.extraHeaders = extraHeaders
    }
}

/// Generic HTTP client for Cloud LLM providers (OpenAI, Anthropic, OpenRouter, etc.)
/// Handles JSON encoding/decoding, retries with exponential backoff, and standard HTTP error mapping.
public actor CloudAPIClient: Sendable {
    private let config: CloudAPIConfig
    private let session: URLSession
    private var requestCount: Int = 0
    private var errorCount: Int = 0

    public init(config: CloudAPIConfig) {
        self.config = config
        
        let configuration = URLSessionConfiguration.default
        configuration.timeoutIntervalForRequest = config.timeout
        configuration.timeoutIntervalForResource = config.timeout * 2
        self.session = URLSession(configuration: configuration)
    }

    /// Performs an HTTP request with retries and decodes the JSON response
    public func performRequest<T: Decodable>(
        endpoint: String,
        method: String = "GET",
        body: Data? = nil,
        responseType: T.Type
    ) async throws -> T {
        let url = config.baseURL.appendingPathComponent(endpoint)
        var request = URLRequest(url: url)
        request.httpMethod = method
        request.setValue("Bearer \(config.apiKey)", forHTTPHeaderField: "Authorization")
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        
        for (key, value) in config.extraHeaders {
            request.setValue(value, forHTTPHeaderField: key)
        }
        
        if let body = body {
            request.httpBody = body
        }
        
        var lastError: Error?
        for attempt in 0..<config.maxRetries {
            do {
                let (data, response) = try await session.data(for: request)
                
                guard let httpResponse = response as? HTTPURLResponse else {
                    throw GemmaServerError.invalidRequestStructure(details: "Invalid response type")
                }
                
                guard (200...299).contains(httpResponse.statusCode) else {
                    let errorBody = String(data: data, encoding: .utf8) ?? "Unknown error"
                    switch httpResponse.statusCode {
                    case 401:
                        throw GemmaServerError.authenticationFailed(details: "Invalid API key")
                    case 429:
                        let retryAfter = httpResponse.value(forHTTPHeaderField: "Retry-After")
                        throw GemmaServerError.rateLimitExceeded(retryAfter: retryAfter)
                    case 500...599:
                        if attempt < config.maxRetries - 1 {
                            let delay = pow(2.0, Double(attempt))
                            try await Task.sleep(nanoseconds: UInt64(delay * 1_000_000_000))
                            continue
                        }
                        throw GemmaServerError.modelInferenceError(details: "API error (HTTP \(httpResponse.statusCode)): \(errorBody)")
                    default:
                        throw GemmaServerError.invalidRequestStructure(details: "HTTP \(httpResponse.statusCode): \(errorBody)")
                    }
                }
                
                let decoder = JSONDecoder()
                let decoded = try decoder.decode(T.self, from: data)
                requestCount += 1
                return decoded
                
            } catch let error as GemmaServerError {
                // If it's a modelInferenceError, it was generated by the 500 block, we can just save it.
                // If it's another API error (like 401 or 400), don't retry.
                if case .modelInferenceError = error {
                    // Handled, will retry if attempts remain
                } else {
                    errorCount += 1
                    throw error
                }
                lastError = error
            } catch {
                lastError = error
                if attempt < config.maxRetries - 1 {
                    let delay = pow(2.0, Double(attempt))
                    try await Task.sleep(nanoseconds: UInt64(delay * 1_000_000_000))
                }
            }
        }
        
        errorCount += 1
        throw lastError ?? GemmaServerError.modelInferenceError(
            details: "Request failed after \(config.maxRetries) attempts"
        )
    }

    /// Performs an HTTP request for Server-Sent Events (SSE) and yields decoded objects
    public func performStreamingRequest<T: Decodable & Sendable>(
        endpoint: String,
        method: String = "POST",
        body: Data? = nil,
        responseType: T.Type
    ) async throws -> AsyncThrowingStream<T, Error> {
        let url = config.baseURL.appendingPathComponent(endpoint)
        var request = URLRequest(url: url)
        request.httpMethod = method
        request.setValue("Bearer \(config.apiKey)", forHTTPHeaderField: "Authorization")
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.setValue("text/event-stream", forHTTPHeaderField: "Accept")
        
        for (key, value) in config.extraHeaders {
            request.setValue(value, forHTTPHeaderField: key)
        }
        
        if let body = body {
            request.httpBody = body
        }
        
        let (result, response) = try await session.bytes(for: request)
        
        guard let httpResponse = response as? HTTPURLResponse else {
            throw GemmaServerError.invalidRequestStructure(details: "Invalid response type")
        }
        
        guard (200...299).contains(httpResponse.statusCode) else {
            // If it's not 200 OK, the body might contain the JSON error.
            // For streams, we won't retry on the fly, just throw the error.
            self.errorCount += 1
            throw GemmaServerError.modelInferenceError(details: "Streaming API error (HTTP \(httpResponse.statusCode))")
        }
        
        self.requestCount += 1
        
        return AsyncThrowingStream { continuation in
            Task {
                do {
                    let decoder = JSONDecoder()
                    for try await line in result.lines {
                        guard line.hasPrefix("data: ") else { continue }
                        let dataString = line.dropFirst("data: ".count).trimmingCharacters(in: .whitespaces)
                        if dataString == "[DONE]" {
                            continuation.finish()
                            return
                        }
                        
                        guard let data = dataString.data(using: .utf8) else { continue }
                        let decoded = try decoder.decode(T.self, from: data)
                        continuation.yield(decoded)
                    }
                    continuation.finish()
                } catch {
                    continuation.finish(throwing: error)
                }
            }
        }
    }

    public func getMetrics() -> (requests: Int, errors: Int) {
        return (requestCount, errorCount)
    }
}
